//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoProps
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Props
    {
        [DataMember]
        public int Property_Id { get; set; }
        [DataMember]
        public string Property_Name { get; set; }
        [DataMember]
        public string Property_Description { get; set; }
        [DataMember]
        public int PhotoPhoto_Id { get; set; }
        [DataMember]
        public virtual Photo Photo { get; set; }
    }
}
